spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.1.122:5432/account_service_database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /accounts
  port: 8081